#### EDIT THIS
title = "Your website"
# repo to publish
githubPublish = "schollz/schollz.github.io"
####
baseURL = ""
languageCode = "en-us"
publishDir = "tmp"
RSSLink = "rss.xml"
enableGitInfo = true
pygmentsCodeFences=true

[permalinks]
  post = "/:slug/"

[params]
  github = "schollz"
  twitter = "yakczar"
  navigation = ["about"]
  analytics=true
  style="4"
  intro = """<p>This site has my notes on recent <a href="/tags/thoughts">thoughts</a>. These thoughts are my own and do not reflect my employer.</p>"""
  quoteServer = "https://randomquote.schollz.com"
  commentServer = "https://guestbook.schollz.com"


[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  written = "written"
  tags = "tags"
  category = "categories"
  keywords = "keywords"